--- Calculate the revenue generated by each product, considering the pricing and the quantity sold.
SELECT
p.Item,
p.Pricing,
SUM(o.Quantity) as Quantity_sold,
ROUND(SUM(p.pricing * o.Quantity), 2) as Total_revenue
FROM products p, orders o
WHERE p.ProductID = o.ProductID
GROUP BY p.Item, p.Pricing;