INSERT INTO [Space objects 2025] VALUES
(1, 'USA', 'North America', 3425), 
(2, 'China', 'Asia', 250), 
(3, 'Russia', 'Eurasia', 40),
(4, 'Italy', 'Europe', 24),
(5, 'France', 'Europe', 23),
(6, 'Germany', 'Europe', 18), 
(7, 'Spain', 'Europe', 16),
(8, 'Japan', 'Asia', 15),
(9, 'Turkey', 'Eurasia', 13), 
(10, 'Finland', 'Europe', 12),
(11, 'Taiwan', 'Asia', 9),
(12, 'UAE', 'Middle east North Africa', 9),
(13, 'UK', 'Europe', 7),
(14, 'Australia', 'Oceania', 7),
(15, 'Israel', 'Middle east North Africa', 7),
(16, 'South Korea', 'Asia', 7), 
(17, 'Canada', 'North America', 6),
(18, 'India', 'Asia', 6),
(19, 'Luxembourg', 'Europe', 5),
(20, 'Greece', 'Europe', 4),
(21, 'Uruguay', 'South America', 4), 
(22, 'Norway', 'Europe', 3),
(23, 'Poland', 'Europe', 3),
(24, 'Czechia', 'Europe', 2),
(25, 'Mexico', 'North America', 2),
(26, 'Pakistan', 'Asia', 2),
(27, 'Portugal', 'Europe', 2),
(28, 'Singapore', 'Asia', 2), 
(29, 'Denmark', 'Europe', 2),
(30, 'Saudi Arabia', 'Middle east North Africa', 2),
(31, 'Bulgaria', 'Europe', 2),
(32, 'Indonesia', 'Asia', 1),
(33, 'Thailand', 'Asia', 1),
(34, 'Hungary', 'Europe', 1),
(35, 'Azerbaijan', 'Eurasia', 1),
(36, 'Belgium', 'Europe', 1),
(37, 'New Zealand', 'Oceania', 1),
(38, 'Ireland', 'Europe', 1),
(39, 'Bahrain', 'Middle east North Africa', 1),
(40, 'Botswana', 'Africa', 1), 
(41, 'Solomon Islands', 'Oceania', 1);
SELECT * FROM [Space objects 2025];
TRUNCATE TABLE [Space objects 2025];